# -*- coding: utf-8 -*-
"""ex1pd.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10OwqXCSkLCTzn0K8B9IKdXVyZcuuiZei
"""

6 -3

"""
Python example

"""
import pandas as pd
pd.__version__

import tensorflow as tf
tf.__version__

"""
series is part of pandas api - 
list looping 
series -concatenation
"""
pd.Series(['SFO','San Jose','sacramento'])

city_name=pd.Series(['SFO','San Jose','sacramento'])
population=pd.Series([345345,565465,132342])
pd.DataFrame({'City_name':city_name,'Population':population})

ca_housing_dataframe=pd.read_csv("https://storage.googleapis.com/mledu-datasets/california_housing_train.csv", sep=",")
ca_housing_dataframe.describe()

"""
histogram counting categories
counting visualization
"""
ca_housing_dataframe.head(8)

ca_housing_dataframe.hist('housing_median_age')

ca_housing_dataframe.hist('population')

cities=pd.DataFrame({'City name':city_name,'Population':population})
print(type(cities['City name']))
cities['City name']

